GET http://localhost:5000/api/v1/restaurants


###
GET http://localhost:5000/api/v1/restaurants?name=food


###

POST http://localhost:5000/api/v1/restaurants/review

Content-Type: application/json

{
    "restaurant_id":"5eb3d668b31de5d588f4292a",
    "text": "good food",
    "name": "john",
    "user_id" : "1234",    
}

###
POST http://localhost:5000/api/v1/restaurants/review

Content-Type: application/json

{
    "restaurant_id":"5eb3d668b31de5d588f4292b",
    "text": "bad food",
    "name": "alp",
    "user_id" : "9876",

    
}

###
PUT http://localhost:5000/api/v1/restaurants/review/5eb3d668b31de5d588f4292a

Content-Type: application/json

{
    "name": "john",
    "user_id" : "1234",
    "text": "great food",
    "review_id":"5eb3d668b31de5d588f4292a"
    
}